spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_admin
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # OPTIONAL: log format
  output:
    ansi:
      enabled: always